name: "create release"

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    outputs:
      SDK_VERSION: ${{ steps.tag-step.outputs.SDK_VERSION }}
    steps:
    - uses: actions/checkout@v4

    - name: Get SDK version and set environment variable
      run: |
        SDK_VERSION=$(grep 'SDK_VERSION' src/GraphConstants.php |  grep -oE '[0-9]+\.[0-9]+\.[0-9A-Za-z.\-]+')
        echo "SDK_VERSION=$SDK_VERSION" >> $GITHUB_ENV

    - id: tag-step
      name: Create and publish tag
      run: |
        echo "SDK_VERSION is:"$SDK_VERSION
        git tag $SDK_VERSION && git push origin $SDK_VERSION
        echo "SDK_VERSION=$SDK_VERSION" >> "$GITHUB_OUTPUT"

  create-release:
    needs: create-tag
    env:
      SDK_VERSION: ${{ needs.create-tag.outputs.SDK_VERSION }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        prerelease: ${{ contains( env.SDK_VERSION, 'RC') }}
        skipIfReleaseExists: true
        tag: ${{ env.SDK_VERSION }}
        name: "Release ${{ env.SDK_VERSION }}"
